In [183]:
##
## Tensor flow, utiliza a distancia dos cossenos para calcular similaridade
## Apenas entre vetores
##

import tensorflow as tf
import numpy as np


x = tf.constant([-0.65576398, -0.30374858, -0.98277804, -0.91493245]) 
y = tf.constant([-0.35576398, -0.30374858, -0.98277804, -0.11493245])
s = tf.losses.cosine_distance(tf.nn.l2_normalize(x, 0), tf.nn.l2_normalize(y, 0), dim=0)
result = tf.Session().run(s)

In [72]:
1-result

0.8367947340011597

In [122]:
##
## scikit-learn, utilizando pairwise_distances 
## É capaz de calcular a distancia entre matrizes
##

from sklearn.metrics.pairwise import pairwise_distances

#base
input_matrix = np.array([[ 1, 2,3 ],[0,0,5]],dtype = 'float32')
    
#resultado
result = (pairwise_distances([[1,0,3]],input_matrix, metric='cosine'))

1-result

array([[0.84515425, 0.9486833 ]])

In [179]:
##
## scikit-learn, utilizando o calculo de visinhos mais próximos
## É capaz de calcular a distancia entre matrizes
##

from sklearn.neighbors import NearestNeighbors
from sklearn.preprocessing import MinMaxScaler
import numpy as np

#                 0              1             2           3           4          5
X = np.array([[-1, -1,36], [-2, -1, 11], [-36, -2, 2], [1, 1, 1], [24, 1, 1], [3, 2, 1]])

# utilizar um metodo escalar para deixar os numeros mais proximos
#treina
scaler = MinMaxScaler()
scaler.fit(X)

#escala
X = scaler.transform(X)

#treinar algoritmo
nbrs = NearestNeighbors(n_neighbors=3, algorithm='brute').fit(X)

#escala
y = scaler.transform([[2,2,-1]])

#resultado
distances, indices = nbrs.kneighbors(y)
indices          

C:\Users\recigio\Anaconda3\lib\site-packages\sklearn\utils\validation.py:475: DataConversionWarning: Data with input dtype int32 was converted to float64 by MinMaxScaler.
  warnings.warn(msg, DataConversionWarning)


array([[5, 3, 4]], dtype=int64)

In [182]:
1-distances

array([[0.94047619, 0.74301151, 0.55255196]])